### ISSUE TITLE
fix user_detail_change args

### ISSUE THREAD

**Issue by smal1378** [smal1378/Bank-3992#23]
https://github.com/smal1378/Bank-3992/blob/f665d932f4cc16acb9e0aacb613f825d19a70912/DS.py#L113

لطفا در این تابع، ورودی تایپ رو بردارید و اجازه بدید شخصی که داره تغییرات رو اعمال میکنه با دادن یوزرنیم به شما بتونه اطلاعات هر یوزری رو تغییر بده بدون اینکه تایپ رو بده به شما.

**Comment by smal1378** [comment]
@MASaraji

**Comment by MASaraji** [comment]
متاسفانه نمی شده همچین کاری کرد

**Comment by smal1378** [comment]
> متاسفانه نمی شده همچین کاری کرد

میشه که، همون روشی ک برای پیدا کردن یوزر توی لاگین چک انجام دادید، همونم اینجا انجام بدید.
