### ISSUE TITLE
What is structure of files?

### ISSUE THREAD

**Issue by farooqkz** [smal1378/Bank-3992#6]
I need to know the structure of code files in order to split the linting workflows so that it's easier to distinguish failed errors in future.
Since it has got 4 parts done by 4 groups, I suppose it's a good idea to split the lint workflows into 4, too!

**Comment by smal1378** [comment]
Cool, For now we've got these modules for each group:

DS:
/DS.py
/DSModels.py

GUI:
/GUI.py
/GUI_Folder/*

DB:
/DB.py

Main:
/main.py

**Comment by farooqkz** [comment]
ok

**Comment by farooqkz** [comment]
test
